// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayerImplementation.Data;

#nullable disable

namespace RepositoryLayerImplementation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307065754_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositoryLayerImplementation.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Author = "J.K Rowling",
                            FullName = "Harry Potter",
                            Genre = "Fantasy",
                            Price = 500f
                        },
                        new
                        {
                            Id = 102,
                            Author = "James Clear",
                            FullName = "Atomic Habits",
                            Genre = "Self Help",
                            Price = 450f
                        },
                        new
                        {
                            Id = 103,
                            Author = "Robert Kiyosaki",
                            FullName = "Rich Dad Poor Dad",
                            Genre = "Finance",
                            Price = 350f
                        },
                        new
                        {
                            Id = 104,
                            Author = "Paulo Coelho",
                            FullName = "The Alchemist",
                            Genre = "Fiction",
                            Price = 300f
                        },
                        new
                        {
                            Id = 105,
                            Author = "J.K Rowling",
                            FullName = "Harry Potter",
                            Genre = "Fantasy",
                            Price = 600f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
